name: testing

on:
  workflow_call:
    inputs:
      rocm_version:
        type: string
        description: ROCm release version
        required: false
        default: "5.1"
      test_me:
        type: string
        description: Test me
        required: false
        default: "2"



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #- name: Checkout new branch
       # uses: actions/checkout@v2
        #with:
          #ref: master
      - name: run echo
        run: echo 'zdravo'
      - name: run if is
        if: "${{ github.event.inputs.rocm_version != '' }}"
        run: echo 'test me'
   #  - name: Checkout new branch
       # uses: actions/checkout@v2
        #with:
         # ref: master
       # run: echo 'cao'